### ISSUE TITLE
Sprite Painter tab doesn't appear anymore

### ISSUE THREAD

**Issue by tayete** [don-tnowe/godot-sprite-painter#16]
I have been using Sprite Painter for a month with no issues (windows 10, Godot 4.1.1), but from some days ago suddenly the plugin tab no longer appears at the top. I have tried reinstalling the addon, checking and unchecking in the project plugins options, to no avail.
Recently I installed a couple of other plugins (hyperlog, yafsm and input helper) but unchecking them doesn't bring back Sprite Painter.

**Comment by don-tnowe** [comment]
They might've changed it, there were discussions on replacing that place with a dedicated UI section for node-specific actions, outside the toolbar. But if you haven't updated Godot for that time, this sure is bizarre.

Are there any errors or warnings in the console? (*i know there are but maybe there are ones that didn't appear before, heh*)

**Comment by tayete** [comment]
Suddenly it came back at the top as usual! I don't know what has happenned 😄 
Maybe it was because of your comment, like taking the car to the workshop! 😉 
Thanks for answering, I really love your plugin!!!
