### ISSUE TITLE
The addon doesn't work 

### ISSUE THREAD

**Issue by MudkipWorld** [don-tnowe/godot-sprite-painter#17]
When I try using the add-on/ plugin in Godot 4.0.2 or 4.1.1, some parts of the code seem broken for some reason. I couldn't figure out how to fix it myself. Will there be any updates coming soon? I really like the concept of the plugin, but I sadly can't use it because of the mentioned issue. 
Example
![Capture](https://github.com/don-tnowe/godot-sprite-painter/assets/94318023/a88632bc-c4f7-450d-8ed4-ab629a0c2db7)

_I even recommend trying to release a non-plugin version as some sort of a demo or simple light-weight drawing app. Would be super cool!_

**Comment by don-tnowe** [comment]
By the way, the fact that some editor-only classes are used means there won't be any standalone app - I'd need to replace references to these classes with my own implemented classes.

**Comment by MudkipWorld** [comment]
> By the way, the fact that some editor-only classes are used means there won't be any standalone app - I'd need to replace references to these classes with my own implemented classes.

Gotcha!, would there any possible way for me to change these classes in some way?
another thing, when I start up the project with the plugin, I always get these. just wanted to make sure they aren't a massive issue ^^;
![screenshot](https://github.com/don-tnowe/godot-sprite-painter/assets/94318023/17368154-a9fd-4635-bd6d-596fb43ea828)

**Comment by don-tnowe** [comment]
Hmm, I'm not getting these. It might be from installing files outside the `addons/sprite_painter` folder (*you're supposed to only have that folder*), or choosing a different directory during install.

What's your project structure?

**Comment by MudkipWorld** [comment]
> Hmm, I'm not getting these. It might be from installing files outside the `addons/sprite_painter` folder (_you're supposed to only have that folder_), or choosing a different directory during install.
> 
> What's your project structure?

Huh, strange, when I closed and reopened Godot, it works now, there are still few messages that appear tho, but the addon now works
